"use client";
import { useState } from "react";
import { Plus, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";

export function JobForm() {
  const [status,setStatus]=useState("draft"); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=new FormData(e.currentTarget);const body=Object.fromEntries(form.entries());body.status=status;const res=await fetch("/api/admin/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json() as {error?:string};setMessage(res.ok?"تم حفظ الوظيفة بنجاح":data.error??"تعذر الحفظ");if(res.ok)e.currentTarget.reset();setBusy(false);}
  const field="mt-2 h-12 w-full rounded-xl border border-slate-200 bg-white px-4 outline-none focus:border-[#00a67e]";
  return <form onSubmit={submit} className="rounded-2xl border bg-white p-6"><div className="mb-6 flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-xl font-black"><Plus className="text-[#00a67e]"/>إضافة وظيفة</h2><p className="mt-1 text-sm font-bold text-slate-500">املأ البيانات الأساسية ثم احفظ كمسودة أو انشر.</p></div></div>
    <div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-black">المسمى الوظيفي بالعربية<input name="titleAr" required className={field}/></label><label className="text-sm font-black">اسم الشركة<input name="company" required className={field}/></label><label className="text-sm font-black">الدولة<input name="country" required className={field}/></label><label className="text-sm font-black">المدينة<input name="city" required className={field}/></label><label className="text-sm font-black">التخصص<input name="category" required className={field}/></label><label className="text-sm font-black">الراتب<input name="salary" className={field} placeholder="اختياري"/></label><label className="text-sm font-black">نمط العمل<NativeSelect name="workMode" className={field}><NativeSelectOption>حضوري</NativeSelectOption><NativeSelectOption>هجين</NativeSelectOption><NativeSelectOption>عن بُعد</NativeSelectOption></NativeSelect></label><label className="text-sm font-black">نوع الدوام<NativeSelect name="employmentType" className={field}><NativeSelectOption>دوام كامل</NativeSelectOption><NativeSelectOption>دوام جزئي</NativeSelectOption><NativeSelectOption>عقد</NativeSelectOption><NativeSelectOption>تدريب</NativeSelectOption></NativeSelect></label><label className="text-sm font-black md:col-span-2">وصف الوظيفة<textarea name="descriptionAr" required className="mt-2 min-h-36 w-full rounded-xl border border-slate-200 p-4 outline-none focus:border-[#00a67e]"/></label></div>
    <div className="mt-6 flex flex-wrap items-center gap-3"><Select value={status} onValueChange={setStatus}><SelectTrigger className="h-11 w-44"><SelectValue/></SelectTrigger><SelectContent dir="rtl"><SelectItem value="draft">حفظ كمسودة</SelectItem><SelectItem value="published">نشر مباشرة</SelectItem></SelectContent></Select><Button disabled={busy} className="h-11 rounded-xl bg-[#00a67e] px-6 font-black hover:bg-[#008f6c]"><Save/>{busy?"جارٍ الحفظ...":"حفظ الوظيفة"}</Button>{message&&<p className="text-sm font-black text-[#007b5f]">{message}</p>}</div>
  </form>;
}
