export const verifiedJobsImport = [
  {
    slug: "oq8-lp-aps-modelling-expert-duqm-2026",
    titleAr: "خبير نمذجة تخطيط وجدولة المصافي",
    titleEn: "Expert LP & APS Modelling - OQ8",
    company: "OQ8",
    country: "عُمان",
    city: "الدقم",
    category: "الهندسة والطاقة",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.oq.com/job/Duqm-Expert-LP-%26-APS-Modelling-OQ8/1439884533/",
    descriptionAr: "تطوير وتحسين نماذج تخطيط وجدولة المصفاة ودعم قرارات التحسين التشغيلي وتعظيم الهوامش في مصفاة الدقم.",
    requirementsAr: ["بكالوريوس في الهندسة الكيميائية أو تخصص تقني ذي صلة", "خبرة متقدمة في نمذجة المصافي والتخطيط", "إجادة اللغة الإنجليزية"],
    status: "published",
    featured: true
  },
  {
    slug: "oq-lead-energy-performance-engineer-muscat-2026",
    titleAr: "مهندس رئيسي لأداء الطاقة",
    titleEn: "Lead Engineer Energy Performance",
    company: "OQ للاستكشاف والإنتاج",
    country: "عُمان",
    city: "مسقط",
    category: "الهندسة والطاقة",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.oq.com/job/Muscat-Lead-Engineer-Energy-Performance/1439244133/",
    descriptionAr: "قيادة نظام إدارة الطاقة ومتابعة مؤشرات الأداء ومبادرات الكفاءة وخفض الانبعاثات في الأصول التشغيلية.",
    requirementsAr: ["مؤهل هندسي مناسب", "خبرة في كفاءة الطاقة وأنظمة إدارتها", "قدرة قوية على تحليل البيانات والتواصل"],
    status: "published",
    featured: true
  },
  {
    slug: "oq-environmental-management-manager-muscat-2026",
    titleAr: "مدير الإدارة البيئية",
    titleEn: "Manager, Environmental Management",
    company: "OQ للاستكشاف والإنتاج",
    country: "عُمان",
    city: "مسقط",
    category: "السلامة والاستدامة",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.oq.com/job/Muscat-Manager%2C-Environmental-Management/1439244433/",
    descriptionAr: "قيادة برامج الإدارة البيئية وضمان الامتثال للأنظمة والسياسات والمعايير الدولية في عمليات الشركة.",
    requirementsAr: ["بكالوريوس في الهندسة أو العلوم البيئية", "خبرة لا تقل عن 8 سنوات في الإدارة البيئية", "خبرة في قطاع النفط والغاز"],
    status: "published"
  },
  {
    slug: "stc-risk-management-analyst-2026",
    titleAr: "محلل إدارة المخاطر",
    titleEn: "Risk Management Analyst",
    company: "stc",
    country: "السعودية",
    city: "الرياض",
    category: "إدارة المخاطر والامتثال",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.stc.com.sa/job/Risk-Management-Analyst/857392723/",
    descriptionAr: "دعم إطار إدارة مخاطر التقنية واستمرارية الأعمال وإعداد خطط المعالجة والتقارير الدورية.",
    requirementsAr: ["بكالوريوس في إدارة المخاطر أو إدارة الأعمال", "خبرة من صفر إلى سنتين", "معرفة بالحوكمة والامتثال"],
    status: "published"
  },
  {
    slug: "stc-ict-applications-developer-857388823-2026",
    titleAr: "مطور تطبيقات تقنية المعلومات والاتصالات",
    titleEn: "ICT Applications Developer",
    company: "stc",
    country: "السعودية",
    city: "الرياض",
    category: "التقنية والبرمجة",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.stc.com.sa/job/ICT-Applications-Developer/857388823/",
    descriptionAr: "المساهمة في تصميم وتطوير الأنظمة والخوادم وقواعد البيانات والبنية التحتية المؤتمتة ودعم تشغيل التطبيقات.",
    requirementsAr: ["بكالوريوس في علوم الحاسب", "خبرة من صفر إلى سنتين", "معرفة بدورة تطوير البرمجيات وقواعد البيانات"],
    status: "published"
  },
  {
    slug: "stc-ict-applications-developer-857388723-2026",
    titleAr: "مطور أنظمة وتطبيقات رقمية",
    titleEn: "ICT Applications Developer",
    company: "stc",
    country: "السعودية",
    city: "الرياض",
    category: "التقنية والبرمجة",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.stc.com.sa/job/ICT-Applications-Developer/857388723/",
    descriptionAr: "تنفيذ اختبارات الأنظمة ودعم البنية التحتية والتطبيقات وتحليل مؤشرات الأداء التقنية.",
    requirementsAr: ["بكالوريوس في علوم الحاسب", "مهارات تحليل وإعداد تقارير", "معرفة بالبنية التقنية وإدارة التطبيقات"],
    status: "published"
  },
  {
    slug: "qatar-airways-customer-services-agent-ii-doha-2026",
    titleAr: "موظف خدمات العملاء",
    titleEn: "Customer Services Agent II - Talent Pool",
    company: "الخطوط الجوية القطرية",
    country: "قطر",
    city: "الدوحة",
    category: "خدمة العملاء",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.qatarairways.com/global/JobDetail/Customer-Services-Agent-II-Join-Our-Talent-Pool/66170",
    descriptionAr: "الانضمام إلى بنك مواهب خدمات العملاء ودعم المسافرين وتقديم تجربة مهنية وفق معايير مجموعة الخطوط الجوية القطرية.",
    requirementsAr: ["مؤهل مناسب", "إجادة التواصل وخدمة العملاء", "إجادة اللغة الإنجليزية"],
    status: "published"
  },
  {
    slug: "qatar-airways-customer-experience-agent-doha-2026",
    titleAr: "موظف تجربة العملاء",
    titleEn: "Customer Experience Agent - Talent Pool",
    company: "الخطوط الجوية القطرية",
    country: "قطر",
    city: "الدوحة",
    category: "خدمة العملاء",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.qatarairways.com/global/JobDetail/Customer-Experience-Agent-Join-Our-Talent-Pool/63319",
    descriptionAr: "دعم عمليات المطار وخدمة المسافرين والمساهمة في تقديم تجربة سفر سلسة وآمنة.",
    requirementsAr: ["خبرة مناسبة في خدمة العملاء", "قدرة على العمل بنظام المناوبات", "مهارات تواصل ممتازة"],
    status: "published"
  },
  {
    slug: "qatar-duty-free-retail-porter-doha-2026",
    titleAr: "عامل خدمات المتاجر",
    titleEn: "Porter - Retail",
    company: "قطر للأسواق الحرة",
    country: "قطر",
    city: "الدوحة",
    category: "التجزئة والضيافة",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.qatarairways.com/global/JobDetail/Porter-Retail/67225",
    descriptionAr: "دعم عمليات متاجر قطر للأسواق الحرة ومناولة المنتجات وترتيبها والمحافظة على جاهزية مناطق البيع.",
    requirementsAr: ["القدرة على العمل الميداني", "الالتزام بمعايير السلامة والخدمة", "الاستعداد للعمل بنظام المناوبات"],
    status: "published"
  },
  {
    slug: "qatar-airways-hr-manager-kuwait-2026",
    titleAr: "مدير الموارد البشرية - الكويت",
    titleEn: "HR Manager - Kuwait",
    company: "الخطوط الجوية القطرية",
    country: "الكويت",
    city: "مدينة الكويت",
    category: "الموارد البشرية",
    employmentType: "دوام كامل",
    workMode: "حضوري",
    salary: "",
    applyUrl: "https://careers.qatarairways.com/global/JobDetail/HR-Manager-Kuwait/67186",
    descriptionAr: "إدارة عمليات الموارد البشرية في الكويت ودعم الأعمال وتطبيق السياسات وتطوير تجربة الموظفين.",
    requirementsAr: ["خبرة قيادية في الموارد البشرية", "معرفة بأنظمة العمل المحلية", "إجادة التواصل بالعربية والإنجليزية"],
    status: "published",
    featured: true
  }
];

export const gulfArticlesImport = [
  {
    slug: "omanisation-guide-oman-jobs",
    title: "دليل التعمين في سلطنة عُمان: ماذا يعني للباحثين عن عمل؟",
    category: "التعمين",
    excerpt: "شرح عملي لمفهوم التعمين والقطاعات التي تمنح الأولوية للكفاءات العُمانية وطريقة قراءة إعلانات الوظائف.",
    content: "ما هو التعمين؟\n\nالتعمين سياسة وطنية تهدف إلى رفع مشاركة المواطنين العُمانيين في سوق العمل وبناء كفاءات محلية قادرة على قيادة القطاعات الاقتصادية. تختلف النسب والوظائف المستهدفة حسب القطاع والقرارات المنظمة.\n\nكيف تقرأ إعلان الوظيفة؟\n\nانتبه إلى عبارة عُماني فقط أو أولوية للعُمانيين، ثم راجع المؤهل والخبرة والموقع قبل التقديم. لا ترسل طلباً عاماً إذا كانت الوظيفة تشترط تخصصاً مختلفاً.\n\nكيف تزيد فرصك؟\n\nاستخدم سيرة ذاتية مختصرة، أبرز التدريب العملي والشهادات التقنية، واكتب المسمى الوظيفي المستهدف بوضوح. تابع بوابات الشركات الرسمية مثل OQ والجهات الحكومية، ولا تدفع أي رسوم مقابل التوظيف.\n\nلغير العُمانيين\n\nتبقى فرص متخصصة متاحة وفق حاجة الشركات والتصاريح النظامية، خصوصاً في الخبرات النادرة والمشروعات الكبرى. تحقق دائماً من شروط الإعلان الرسمي.",
    imageUrl: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80",
    readTime: "7 دقائق",
    status: "published"
  },
  {
    slug: "kuwaitisation-jobs-guide",
    title: "تكويت الوظائف في الكويت: القطاعات والفرص وطريقة التقديم",
    category: "تكويت الوظائف",
    excerpt: "ما المقصود بتكويت الوظائف وكيف ينعكس على فرص المواطنين والباحثين عن تخصصات مطلوبة في الكويت؟",
    content: "ما هو تكويت الوظائف؟\n\nتكويت الوظائف يهدف إلى زيادة نسبة المواطنين الكويتيين في سوق العمل، ويظهر أثره في الجهات الحكومية والشركات والقطاعات المنظمة بنسب عمالة وطنية.\n\nأين توجد الفرص؟\n\nتظهر فرص في الاتصالات والبنوك والطاقة وخدمة العملاء والتقنية والموارد البشرية. بعض الإعلانات تشترط الجنسية الكويتية بوضوح، بينما تبقى وظائف تخصصية أخرى مفتوحة وفق احتياجات صاحب العمل.\n\nقبل التقديم\n\nراجع الجنسية المطلوبة، المؤهل، سنوات الخبرة والموعد النهائي. استخدم رابط الشركة الرسمي وتجنب إرسال الوثائق الحساسة إلى حسابات غير موثقة.\n\nتحسين الطلب\n\nاربط خبراتك بمتطلبات الإعلان، وأضف المهارات التقنية واللغات والإنجازات بالأرقام بدلاً من الاكتفاء بقائمة واجبات عامة.",
    imageUrl: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1400&q=80",
    readTime: "7 دقائق",
    status: "published"
  },
  {
    slug: "official-gulf-job-portals-guide",
    title: "كيف تتحقق من الوظائف الحقيقية في الخليج قبل التقديم؟",
    category: "نصائح التوظيف",
    excerpt: "علامات تساعدك على تمييز الإعلان الرسمي من الإعلان الوهمي وحماية بياناتك أثناء البحث عن عمل.",
    content: "ابدأ من المصدر\n\nابحث عن الوظيفة في صفحة التوظيف الرسمية للشركة وقارن المسمى والموقع ورقم الطلب. وجود الإعلان في منصة أخرى لا يكفي إذا تعذر العثور عليه في المصدر.\n\nعلامات الخطر\n\nلا تدفع رسوماً مقابل المقابلة أو التأشيرة، ولا تشارك بيانات البطاقة البنكية أو رمز التحقق. انتبه إلى البريد المجاني والرسائل التي تعد بالتوظيف من دون مقابلة.\n\nافحص الرابط\n\nتأكد من اسم النطاق ومن اتصال HTTPS، وادخل إلى بوابة الشركة يدوياً عند الشك. اقرأ الموعد النهائي واحفظ نسخة من الإعلان ورقم الطلب.\n\nالطلب الجيد\n\nخصص السيرة لكل وظيفة، واستعمل الكلمات الموجودة في وصفها بطريقة طبيعية، ثم تابع حالة الطلب من حسابك في البوابة الرسمية.",
    imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1400&q=80",
    readTime: "6 دقائق",
    status: "published"
  },
  {
    slug: "gulf-career-portals-profile-guide",
    title: "طريقة إنشاء ملف قوي في بوابات توظيف شركات الخليج",
    category: "السيرة الذاتية",
    excerpt: "خطوات عملية لتعبئة الملف المهني ورفع السيرة واختيار الكلمات التي تساعد مسؤولي التوظيف على العثور عليك.",
    content: "جهز المعلومات أولاً\n\nاكتب نسخة موحدة من بيانات التعليم والخبرة والتواريخ، وجهز سيرة PDF باسم مهني واضح. تأكد من تطابق المعلومات بين النموذج والسيرة.\n\nالعنوان والمهارات\n\nاستخدم مسمى وظيفياً محدداً وأضف المهارات المرتبطة فعلاً بخبرتك. لا تضع عشرات الكلمات غير المرتبطة بهدف الظهور في كل بحث.\n\nالإنجازات\n\nحوّل المهام إلى نتائج قابلة للقياس مثل خفض الوقت أو زيادة المبيعات أو تحسين جودة الخدمة. هذه التفاصيل تجعل الملف أكثر إقناعاً.\n\nالتحديث والمتابعة\n\nحدث الملف عند اكتساب شهادة أو خبرة جديدة، وفعل التنبيهات المناسبة، لكن تجنب إرسال طلبات عشوائية إلى وظائف لا تناسب مؤهلاتك.",
    imageUrl: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1400&q=80",
    readTime: "6 دقائق",
    status: "published"
  }
];
